### ISSUE TITLE
How to use

### ISSUE THREAD

**Issue by guyluz11** [BinghamtonRover/Dashboard#127]
If I understand correctly after running the app I should also run the [video](https://github.com/BinghamtonRover/Video) package, currently have a problem defining the path of my camera in the video package and I opened an issue about it.

But I saw that Dashboard is Listening on different ports than the video package
Dashboard:
```dart
flutter: [I]  Listening on port 52080
flutter: [I]  Listening on port 55503
flutter: [I]  Listening on port 51762
```

Video:
```dart
[I]  Listening on port 8002
[I]  Video program initialized
```

What am I missing, are they separate programs?

**Comment by guyluz11** [comment]
Found it, here are the instructions

1. Video camera path should get specified manually in the [video repo](https://github.com/BinghamtonRover/Video) under constants.dart file
2. In this rpo run the app and insert your video device ip
First on the cog in the top right corner (the upper one) 
![image](https://github.com/BinghamtonRover/Dashboard/assets/9304740/73adbd18-f467-42aa-b6c5-aa5347214fdf)
then set IP of the device running the video repo program in the video socket row 
![image](https://github.com/BinghamtonRover/Dashboard/assets/9304740/9c575eb7-e15e-44c3-9167-5e4153103de7)
3. Now click save.
4. Exit the app! and open it again for the changes to take effect.

The instructions should be added to the readme.

Have to say that this project is very impressive and important to the dart ecosystem.
You have created a package for OpenCV which is very important for using the camera of devices and even more to open the option of detecting movement, face recognition and more.

And also you have demonstrated a way to send video through the network with the video repo.
Still need to figure out which protocol you have used to send the video and to see if I can listen multiple times to the same stream of video :).

Thanks guys for the hard work and I hope you will win the Marse Rover competition

**Comment by Levi-Lesches** [comment]
First of all, props to you for being able to piece them together with the little docs we have so far. 

Secondly, this project is internal to the Binghamton University Mars Rover Team, as well as all other projects in this GitHub Organization, so I'm not sure what use it would be to document usage to the public as the public does not have our exact hardware/software setup. We do have more docs in the works, but they're mostly internal for this reason. Our code is open-source to share with those interested in how we do our work, but the programs themselves are only designed to work with what we need them to.

> You have created a package for OpenCV which is very important for using the camera of devices and even more to open the option of detecting movement, face recognition and more.

The `opencv_ffi` package is released under my personal account and _is_ public, and published [here](https://pub.dev/packages/opencv_ffi) on Pub. That package, for now, will also focus on the needs of the team but will grow to meet the needs of the Dart community.

> Still need to figure out which protocol you have used to send the video and to see if I can listen multiple times to the same stream of video :)

We use Protobuf messages, with a `bytes` field that we literally just store the entire JPG in and send it as-is. The Dashboard can command the Video program to run at different resolutions, framerates, and compressions in order to not strain our network. These Protobuf messages are sent as UDP packets, hence all the "socket" terminology.

**Comment by guyluz11** [comment]
> so I'm not sure what use it would be to document usage to the public as the public does not have our exact hardware/software setup. 

I have used part of your system tonight (dashboard connected to video), as a security camera for my door 😆.
My country is at war and I wanted to know what happens outside my home when I am in the missile shelter.
Solving that for cenario were there is no electricity/Wi-Fi or cellular network where crucial.
With your methods I should be able to open hotspot between two phones, and share video directly without the cloud and can stay safe in the shelter.
Finding two phones should be more common for others, but for now I have decided to use it with raspberry pi as a standalone security camera.

I created a script that start the Video program on raspberry pi whenever it boots, connected a USB camera to it and it worked 😁

![Screenshot_20231010_081223](https://github.com/BinghamtonRover/Dashboard/assets/9304740/4979e18f-cdab-4eae-a403-0a7efaf017a3)

I wanted to do it specifically in dart (even though python is probably a better candidate) and this project pieced together a lot of important parts.

I'm not sure how important it is to add documentation so you can probably keep it like this.

Next step is to add motion detection that will notify my phone of a movement.
That way I can check if there is a terrorist in my door and gets ready even while I'm sleeping.

The are better ways to transfer video like RPRS, RTP, GPRS but not necessarily better for your use case, maybe I will explore it as well

**Comment by Levi-Lesches** [comment]
> I have used part of your system tonight (dashboard connected to video), as a security camera for my door 😆.
My country is at war and I wanted to know what happens outside my home when I am in the missile shelter.
Solving that for cenario were there is no electricity/Wi-Fi or cellular network where crucial.

Wow, I'll admit I did not think there were real use-cases for this, but we will definitely up our documentation efforts and make them more public! We have an internal docs site that explains the exact technologies we use on the rover, with a heavy focus on the Pis, but I'll make sure our READMEs are more to-the-point and explain how to get started. 

If you need more resources, we also have a repository that hosts all of our raspberry Pi code that would have made your setup much easier. I regret not sharing it earlier but it may not be 100% complete until I push more code tonight: 

https://github.com/BinghamtonRover/SecondaryPi

It includes a setup script to download all the repos, including OpenCV, build everything, and configure `systemd` to launch on boot, but you seem to have gotten that down already. If your camera keeps re-assigning IDs (eg, from `/dev/video0` to `/dev/video2`), we have a udev file that can fix that. It's pretty tailored to our use-case but you can modify it for your cameras.

If you need any help with anything, please feel free to reach out to me at levilesches@gmail.com and I can help you set up anything else or debug other issues (we can also move from there to another form of DM). I'll be happy to help add/test any other OpenCV functionality you need and help with general Dart debugging, as well as extending a fork of the dashboard/video to cover more of your needs (like listening on multiple streams).

We will update both this and the Video repository throughout the year but most of the changes you'll see here will probably not be video-related. We do hope to improve FPS on the video soon though. 

> The are better ways to transfer video like RPRS, RTP, GPRS but not necessarily better for your use case, maybe I will explore it as well, but for now it works and I can relax

We did look into RTP, but decided UDP was simple enough and works well enough that the extra hassle wasn't actually worth it. In our case, we simply stream JPG images one-by-one and the dashboard just switches to the next one really fast. We don't actually use any real-time or video protocols at all.

**Comment by guyluz11** [comment]
You already helped so much there is no reason to regret anything 😁
Also I used only the Video part.

I have decided to included this in an Android app to make it more accessible, people could use it with a spare phone that they already have, also phone already have a battery which is a plus when there isn't electricity.
Probably will integrate this into my old open source startup about smart devices, and consider the phone as a smart device witch can count as security camera.
The phones will find each other automatically and configure IP in the network and secondary
network (hotspot) information for when the WiFi is getting down 

Will try to find time to work on that, it will help if you can make Video work on the phone 
https://github.com/Levi-Lesches/opencv_camera/issues/1


Ha ha if sending JPG works then it is great

**Comment by Levi-Lesches** [comment]
Sadly as I mentioned in that issue, it seems the C++ version of OpenCV does not work on Android (maybe iOS too), and you'd need to use either the Java-based OpenCV package or the standard `package:camera`. We have no plans to add the Java version to `opencv_ffi` anytime soon, as we plan to keep it all FFI-based.

**Comment by guyluz11** [comment]
Ok for now will use different package only for phones.

Just curious, in your estimation after "Native assets feature" get add is there a reason for it not to work?

**Comment by Levi-Lesches** [comment]
Yes, the native assets feature will just make it easier to compile OpenCV. That's not a problem today, you can just run the `build.sh` or `build.bat` scripts. 

On mobile, permissions are very locked down -- usually, iOS more than Android. But as you saw in https://github.com/Levi-Lesches/opencv_ffi/issues/8#issuecomment-1740521961, apps are not allowed to access `/dev/video0`, or at least you need the official Android NDK. I'm not an expert on Android cameras but that's what I found when Googling. If you find a way to get that to work, let me know and I'd be more than happy to add Android to the list.
