### ISSUE TITLE
Implement a UDP networking service

### ISSUE THREAD

**Issue by Levi-Lesches** [BinghamtonRover/Dashboard#5]
We need a `RoverNetwork` service that can: 
- establish a connection with the rover (it's UDP, so probably just a few pings)
- send messages to the rover as serialized Protobuf messages
- receive Protobuf messages from the rover

Loosely going from the above, we'd probably need the following:
```dart
class RoverNetwork extends Service {
  Future<void> init();  // send pings until receive response
  Future<void> send(RoverMessage message);  // sends a message to the rover
  Stream<RoverMessage> incomingMessages;  // receives incoming messages from the rover
}
```

We'd use a stream for incoming messages since `dart:io` uses it for its [`RawDatagramSocket`](https://api.dart.dev/stable/2.17.3/dart-io/RawDatagramSocket-class.html) UDP implementation. It will also help the front end, which has built-in support for updating widget values based on data from a `Stream` object.

**Comment by superdan-t** [comment]
This is blocked by the draft issue `Revise network message-passing protocol for inter-language implementation`.

It might be worth putting in a separate repo with the other network stuff but we can decide that when the task is unblocked.

(Also bumped from med to large since I think this is one of the bigger tasks)

**Comment by Levi-Lesches** [comment]
We've decided to go with a Stream-like API, but without directly exposing streams. We're using: 
```dart
class MessageSender extends Service {
  /// Wraps [message] in a [WrapperMessage] and sends over UDP.
  Future<void> send(Message message);   
}

class MessageReceiver extends Service {
  /// Runs [handler] with the message decoded by [decoder] whenever a message of type [name] appears.
  void registerHandler<T extends Message>({
    required String name, 
    required MessageDecoder<T> decoder, 
    required Handler<T> handler
  });
}
```
